Repository fybx/blog, pull requests merged in 2022-03, with the labels that each got.

#1 Implement custom 404 redirect page
  404.html
  scripts/typewriter.js
  styles/404.css
Labels: feature

#2 Fix 404 page viewing issues when viewport <= 1000px
  404.html
  index.php
  scripts/typewriter.js
  styles/404.css
Labels: bug

#3 Add tribute page and apply viewport fix
  footer.html
  index.html
  scripts/tribute.js
  styles/general.css
  tribute.html
Labels: bug, feature

#4 Visual update to 404 page
  scripts/typewriter.js
  styles/404.css
Labels: feature

#5 Maintenance and content update
  footer.html
  index.html
  styles/404.css
  templates/root-level.html
Labels: correction

#6 Cosmetic update
  android-chrome-192x192.png
  android-chrome-512x512.png
  apple-touch-icon.png
  favicon-16x16.png
  favicon-32x32.png
  favicon.ico
  header.html
  headerD.html
  images/photo.jpg
  images/photo.png
  index.html
  site.webmanifest
Labels: feature, correction
